name: Build, run test and upload binaries 

on: [push, pull_request]

jobs:

  test-linux:
    runs-on: "ubuntu-20.04"
    steps:
    - uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M')"

    - name: Install build dependencies
      run: sudo apt -y update && sudo apt -y install ncat libpcap-dev libsdl-dev

    - name: Install test dependencies
      run: sudo apt -y update && sudo apt -y install ncat

    - name: Create build environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wall"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release
      env:
        MAKEFLAGS: "-j2"

    - name: Run test scripts
      working-directory: ${{runner.workspace}}/axpbox
      shell: bash
      run: ${{runner.workspace}}/axpbox/test/run

    - name: Upload AXPbox artifact
      uses: actions/upload-artifact@v1
      with:
        name: AXPbox-linux-test-${{ env.BUILD_DATE }}
        path: ${{runner.workspace}}/build/axpbox 
      env:
        BUILD_DATE: ${{ steps.date.outputs.date }}

  build-linux-clang:
    runs-on: "ubuntu-20.04"

    steps:
    - uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M')"

    - name: Install build dependencies
      run: sudo apt -y update && sudo apt -y install libpcap-dev libsdl-dev

    - name: Create build environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wall"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release
      env:
        MAKEFLAGS: "-j2"

    - name: Upload AXPbox binary
      uses: actions/upload-artifact@v1
      with:
        name: AXPbox-linux-clang-${{ env.BUILD_DATE }}
        path: ${{runner.workspace}}/build/axpbox 
      env:
        BUILD_DATE: ${{ steps.date.outputs.date }}

  build-linux-gcc:
    runs-on: "ubuntu-20.04"

    steps:
    - uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M')"

    - name: Install build dependencies
      run: sudo apt -y update && sudo apt -y install libpcap-dev libsdl-dev

    - name: Create build environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wall"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release
      env:
        MAKEFLAGS: "-j2"

    - name: Upload AXPbox binary
      uses: actions/upload-artifact@v1
      with:
        name: AXPbox-linux-gcc-${{ env.BUILD_DATE }}
        path: ${{runner.workspace}}/build/axpbox
      env:
        BUILD_DATE: ${{ steps.date.outputs.date }} 

  build-windows-msvc:
    runs-on: windows-2019
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M')"

    - name: Create build environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wall"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release
      env:
        MAKEFLAGS: "-j2"

    - name: Upload AXPbox Binary
      uses: actions/upload-artifact@v1
      with:
        name: AXPbox-windows-msvc-${{ env.BUILD_DATE }}.exe
        path: ${{runner.workspace}}/build/axpbox 
      env:
        BUILD_DATE: ${{ steps.date.outputs.date }} 

  build-osx-appleclang:
    runs-on: "macos-10.15"
    continue-on-error: true
    
    steps:
    - uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M')"

    - name: Create build environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Install dependencies
      run: brew install coreutils libpcap netcat # sdl2 libx11

    - name: gnu tr
      run: sudo mv /usr/local/opt/coreutils/libexec/gnubin/tr /usr/bin/tr

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wall -Wc++11-extensions -Wc++11-long-long -Wc++11-extra-semi -std=c++11 -stdlib=libc++ -I/usr/local/opt/libpcap/include"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release
      env:
        MAKEFLAGS: "-j2"

    - name: Upload AXPbox Binary
      uses: actions/upload-artifact@v1
      with:
        name: AXPbox-osx-appleclang-${{ env.BUILD_DATE }}
        path: ${{runner.workspace}}/build/axpbox 
      env:
        BUILD_DATE: ${{ steps.date.outputs.date }} 

